[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan serve --port=$PORT --host=0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "${RAILWAY_STATIC_URL}"
CACHE_DRIVER = "redis"
SESSION_DRIVER = "redis"
QUEUE_DRIVER = "redis"
LOG_LEVEL = "error"
LOG_CHANNEL = "stack"
BROADCAST_DRIVER = "pusher"
FILESYSTEM_DISK = "s3" 