[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev && npm install && npm run build && php artisan optimize"

[deploy]
startCommand = "php artisan serve --port=$PORT --host=0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "redis"
SESSION_DRIVER = "redis"
QUEUE_DRIVER = "redis"
LOG_LEVEL = "error"
LOG_CHANNEL = "stack"
BROADCAST_DRIVER = "pusher"
FILESYSTEM_DISK = "s3" 